image: $CI_REGISTRY_IMAGE/ci-build-runner:$CI_COMMIT_REF_SLUG
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - prepare
  - build-lib
  - build
  - test
  - release

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

default:
  before_script:
    - mkdir -p build
    - cd build || exit
  cache:
    paths:
      - "build/*"

trigger-prepare:
  stage: prepare
  trigger:
    strategy: depend
    include: .prepare.gitlab-ci.yml

prepare-release:
  stage: prepare
  image: alpine:latest
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"'
  before_script:
    - apk add curl jq
  script:
    - 'curl -H "PRIVATE-TOKEN: $CI_API_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/changelog?version=$CI_COMMIT_TAG" | jq -r .notes > release_notes.md'
    - cat release_noted.md
  artifacts:
    paths:
      - release_notes.md

build-library:
  stage: build-lib
  needs:
    - trigger-prepare
  script:
    - cmake ..
    - make oCLFFTsup -j $(nproc)
  artifacts:
    paths:
      - build/lib/liboCLFFTsup.so

build-lookup:
  stage: build-lib
  needs:
    - trigger-prepare
  script:
    - cmake ..
    - make play-lookup play-lookup-fp32
    - ./playground/play-lookup > ../oclfft/ard-ocl/src/lookup.cl
    - ./playground/play-lookup > ../oclfft/bit-ocl/src/lookup.cl
    - ./playground/play-lookup > ../oclfft/flk-ocl/src/lookup.cl
    - ./playground/play-lookup-fp32 > ../oclfft/flk-ocl-fp32/src/lookup.cl
  artifacts:
    paths:
      - oclfft/**/lookup.cl

build-documents:
  stage: build
  needs:
    - trigger-prepare
  script:
    - cd $CI_PROJECT_DIR/proposal || exit
    - texi2pdf proposal.tex
    - cd $CI_PROJECT_DIR/report || exit
    - texi2pdf report.tex
  artifacts:
    paths:
      - "*/*.pdf"

build-documentation:
  stage: build
  needs:
    - trigger-prepare
  script:
    - cmake -DENABLE_DOXYGEN=on ..
    - make doxygen
  artifacts:
    paths:
      - "docs/*"

build-binaries:
  stage: build
  needs:
    - trigger-prepare
    - build-lookup
    - build-library
  script:
    - cmake -DENABLE_DOXYGEN=off ..
    - make ard-ocl
    - make ard-omp
    - make ard-seq
    - make bit-ocl
    - make dft-seq
    - make dft-seq-fp32
    - make flk-ocl
    - make flk-ocl-fp32
    - make rms-error
    - make play-objcopy
    - make play-example
    - make play-reversegen
  artifacts:
    paths:
      - "*/**/play-objcopy"
      - "*/**/play-example"

test:
  stage: test
  needs:
    - trigger-prepare
    - build-binaries
  variables:
    CTEST_OUTPUT_ON_FAILURE: 1
  script:
    - make test

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  environment: gitlab-releases
  needs:
    - job: prepare-release
      artifacts: true
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"'
  before_script:
    - echo "Creating release ${CI_COMMIT_TAG}"
  script:
    - cat release_noted.md
  release:
    name: '${CI_COMMIT_TAG}'
    description: release_notes.md
    tag_name: '${CI_COMMIT_TAG}'
    ref: '$CI_COMMIT_SHA'